### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by traincrisis** [Fridtjof-DE/MinecartTrains#6]
Can you please make a version of this plugin to a forge/fabric mod? Just i want to use it in singleplayer + i don't know how to make a spigot/bukkit/paper server

**Comment by vico93** [comment]
I second this, specially if the plugin aims to be an alternative to TrainCarts - the author of that doesn't have interest of making a Fabric version, and the only alternative for Fabric is Linkart, but it still doesn't have a 1.20.6 version.

**Comment by vico93** [comment]
any news? @Fridtjof-DE

**Comment by Fridtjof-DE** [comment]
Sorry, but I have no plans to bring the plugin to another loader.
